### PR TITLE
Sync to upstream

### PR DESCRIPTION
**Pull request by marchingphoenix**
Adds python wheel for windows and other bug fixes.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @bibi21000, @dude0001, @derEisele, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;python-openzwave#1).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by marchingphoenix** [comment]
hmm, this might not work. Feel free to kill if it won't.
Propose syncing to upstream to fix https://github.com/home-assistant/home-assistant/issues/18552

**Comment by pvizeli** [comment]
I have a simple task they can do it. I'll run it later

**Comment by homeassistant** [comment]
Hi @bibi21000, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;python-openzwave#1).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @bibi21000, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;python-openzwave#1).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by dude0001** [comment]
@pvizeli what is the plan for getting these changes in to the home-assistant/python-openzwave fork? Is there something else I need to do?

**Comment by pvizeli** [comment]
Pick up only the changes to a PR

**Pull request closed without merging**
