### PR TITLE
pyozw_setup.py: Add support for NetBSD

### PR DESCRIPTION
**Pull request by gdt**
This is mostly copying the FreeBSD support, and specifying libusb-1.0
as the name for the usb1 library.

With this commit, I can run setup.py build/install on NetBSD 8, and successfully use openzwave from within HA.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @gdt, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;python-openzwave#5).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by gdt** [comment]
I don't understand the CI failure; it looks like a disagreement between the upstream version number and the homeassistant version number.  I don't see anything in my commit that changes version numbers.

**Comment by gdt** [comment]
Thanks very much for merging my PR, especially in the face of a doing-zwave-differently future, some day.

**Comment by pvizeli** [comment]
There come a lot of changes with zwave in the first Q1/Q2. The library will be not needed anymore

**Pull request merged**
